Repository ValentinaTenus/reviewED_fe, pull requests merged in 2024-10, with the labels that each got.

#59 Courses filter
  .env.exapmle
  src/common/components/header/styles.module.scss
  src/common/components/index.ts
  src/common/components/logo/index.tsx
  src/common/components/logo/styles.module.scss
  src/common/components/search-bar/index.tsx
  src/common/components/star-rating/styles.module.scss
  src/common/constants/image-upload-url.ts
  src/common/constants/index.ts
  src/common/constants/logo-none.ts
  src/common/enums/courses-filter-type.enum.ts
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card-desktop/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/company-card/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-result-items/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-result-items/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-result-title/index.tsx
  src/pages/course-list-page/components/course-list/index.tsx
  src/pages/home-page/components/main-content/components/companies-section/components/company-card/index.tsx
  src/pages/home-page/components/main-content/components/course-card/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
  src/redux/courses/courses-slice.ts
Labels: enhancement

#60 add sort for courses, change styles
  src/common/components/search-bar/index.tsx
  src/common/constants/courses-sort-options.ts
  src/pages/course-list-page/components/course-list/components/filter-result-items/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-result-title/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-result-title/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-section/index.tsx
  src/pages/course-list-page/components/course-list/index.tsx
  src/pages/course-list-page/components/course-list/styles.module.scss
Labels: enhancement

#42 Moderation page
  src/common/components/header/index.tsx
  src/common/components/icon-button/index.tsx
  src/common/components/modal/index.tsx
  src/common/components/modal/styles.module.scss
  src/common/components/search-bar/index.tsx
  src/common/components/search-bar/styles.module.scss
  src/common/components/sort-dropdown/index.tsx
  src/common/components/sort-dropdown/styles.module.scss
  src/common/components/toggle-group-buttons/index.tsx
  src/common/constants/index.ts
  src/common/constants/moderations-review-period-sort-options.ts
  src/common/constants/moderations-review-status-sort-options.ts
  src/common/enums/index.ts
  src/common/enums/moderation-review-buttons-group.enum.ts
  src/common/enums/moderation-review-status.ts
  src/common/hooks/index.ts
  src/common/hooks/transform-date.hook.ts
  src/common/types/dropdown-option/index.ts
  src/common/types/index.ts
  src/common/types/review/get-moderation-reviews.ts
  src/common/types/review/index.ts
  src/pages/companies-list-page/components/companies-list/components/filter-section/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/index.tsx
  src/pages/faq-page/components/main-content/components/question-and-answer-section/index.tsx
  src/pages/home-page/components/main-content/index.tsx
  src/pages/moderators-page/components/main-content/components/filter-section/index.tsx
  src/pages/moderators-page/components/main-content/components/filter-section/styles.module.scss
  src/pages/moderators-page/components/main-content/components/index.ts
  src/pages/moderators-page/components/main-content/components/review-card/index.tsx
  src/pages/moderators-page/components/main-content/components/review-card/styles.module.scss
  src/pages/moderators-page/components/main-content/index.tsx
  src/pages/moderators-page/components/main-content/styles.module.scss
  src/redux/reviews-moderation/constans.ts
  src/redux/reviews-moderation/reviews-moderation-api.ts
  src/redux/reviews-moderation/reviews-moderation-slice.ts
  src/redux/reviews-moderation/use-review-moderation-api.hook.ts
Labels: enhancement

#61 Companies page
  src/common/constants/companies-links/companies-links-desktop.ts
  src/common/constants/companies-links/companies-links-smartphones.ts
  src/common/constants/companies-links/companies-links-tablets.ts
  src/common/constants/companies-sort-options.ts
  src/common/constants/courses-links/courses-links-desktop.ts
  src/common/constants/courses-links/courses-links-smartphones.ts
  src/common/constants/courses-links/courses-links-tablets.ts
  src/common/constants/courses-sort-options.ts
  src/common/enums/app-route.enum.ts
  src/common/types/company/get-companies-request-query.type.ts
  src/pages/companies-list-page/components/companies-list/components/filter-section/components/companies-categories/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filter-section/index.tsx
  src/pages/companies-list-page/components/companies-list/index.tsx
  src/pages/course-list-page/components/course-list/index.tsx
  src/redux/companies/companies-api.ts
  src/redux/companies/companies-slice.ts
Labels: documentation, enhancement

#62 Code refactor
  src/common/components/check-dropdown/index.tsx
  src/common/types/company/get-company-response-dto.type.ts
  src/common/types/company/index.ts
  src/common/types/courses/course.type.ts
  src/common/types/courses/get-courses-response-dto.type.ts
  src/common/types/courses/index.ts
  src/common/types/get-query-response.type.ts
  src/common/types/index.ts
  src/common/types/review/get-company-and-course-review-by-user-response-dto.type.ts
  src/common/types/review/get-reviews-response.type.ts
  src/common/types/review/index.ts
  src/common/types/review/review.type.ts
  src/pages/course-list-page/components/course-list/index.tsx
  src/pages/home-page/components/main-content/components/new-courses-section/index.tsx
  src/pages/home-page/components/main-content/components/top-courses-section/index.tsx
  src/redux/companies/companies-api.ts
  src/redux/courses/courses-api.ts
  src/redux/reviews/constants.ts
  src/redux/reviews/reviews-api.ts
  src/redux/reviews/reviews-companies-api.ts
Labels: enhancement

#63 Code refactor
  src/common/types/index.ts
  src/common/types/review/get-reviews-by-company-id-response-dto.type.ts
  src/common/types/review/index.ts
  src/pages/company-details-page/components/company-details/components/courses/components/course-card/course-card.tsx
  src/pages/company-details-page/components/company-details/components/courses/courses.tsx
  src/pages/home-page/components/main-content/components/course-card/index.tsx
  src/pages/home-page/components/main-content/components/new-courses-section/index.tsx
  src/pages/home-page/components/main-content/components/top-courses-section/index.tsx
  src/pages/home-page/components/main-content/index.tsx
  src/redux/companies/companies-api.ts
  src/redux/courses/courses-api.ts
Labels: enhancement

#66 Moderation page
  src/common/types/review/get-moderation-reviews.ts
  src/common/types/review/index.ts
  src/pages/moderators-page/components/main-content/components/review-card/index.tsx
  src/pages/moderators-page/components/main-content/components/review-card/styles.module.scss
  src/pages/moderators-page/components/main-content/index.tsx
  src/redux/reviews-moderation/reviews-moderation-api.ts
  src/redux/reviews-moderation/use-review-moderation-api.hook.ts
Labels: enhancement

#67 add changes
  src/common/components/course-card/index.tsx
  src/common/components/footer/index.tsx
  src/common/components/icon/icon-name-to-svg.ts
  src/common/components/logo/styles.module.scss
  src/common/components/pagination/index.tsx
  src/common/constants/index.ts
  src/common/constants/other-footer-links.ts
  src/common/enums/icon-name.enum.ts
  src/common/types/get-query-response.type.ts
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-result-title/index.tsx
  src/pages/course-list-page/components/course-list/index.tsx
  src/pages/home-page/components/main-content/components/companies-section/components/company-card/styles.module.scss
  src/pages/home-page/components/main-content/components/course-card/index.tsx
  src/pages/home-page/components/main-content/components/course-card/styles.module.scss
  src/pages/home-page/components/main-content/components/top-courses-section/index.tsx
Labels: bug

#72 Code refactor
  src/assets/images/call.svg
  src/assets/images/sms.svg
  src/common/components/footer/components/social-media-links/styles.module.scss
  src/common/components/footer/components/tech-contacts-block/index.tsx
  src/common/components/footer/components/tech-contacts-block/styles.module.scss
  src/common/components/footer/index.tsx
  src/common/components/footer/styles.module.scss
  src/common/components/search-bar/styles.module.scss
  src/common/components/search-input/styles.module.scss
  src/common/components/sort-dropdown/index.tsx
  src/common/components/sort-dropdown/styles.module.scss
  src/common/components/view-tabs/styles.module.scss
  src/common/constants/screen-breakpoints.ts
  src/pages/companies-list-page/components/companies-list/components/filter-section/components/companies-categories/components/company-category/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filter-section/components/filter-section-text/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filter-section/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filter-section/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/company-card/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/styles.module.scss
  src/pages/company-details-page/components/company-details/components/courses/courses.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
  src/pages/company-details-page/components/company-details/components/reviews/reviews.tsx
Labels: bug

#75 changed styles on home page
  src/assets/images/logo.svg
  src/common/components/header/styles.module.scss
  src/common/components/input/index.tsx
  src/common/components/input/styles.module.scss
  src/common/components/pagination/index.tsx
  src/common/components/sort-dropdown/styles.module.scss
  src/pages/companies-list-page/components/companies-list/index.tsx
  src/pages/companies-list-page/styles.module.scss
  src/pages/home-page/components/main-content/components/add-company/index.tsx
  src/pages/home-page/components/main-content/components/add-company/styles.module.scss
  src/pages/home-page/components/main-content/components/course-card/styles.module.scss
  src/pages/home-page/components/main-content/styles.module.scss
  src/redux/auth/auth-slice.ts
  src/redux/services.ts
Labels: enhancement

#77 Moderation page => sortDropdown (and group)
  src/assets/images/close-circle.svg
  src/common/components/button/styles.module.scss
  src/common/components/icon/icon-name-to-svg.ts
  src/common/components/sort-dropdown/index.tsx
  src/common/components/sort-dropdown/styles.module.scss
  src/common/constants/moderations-review-period-sort-options.ts
  src/common/constants/moderations-review-status-sort-options.ts
  src/common/enums/icon-name.enum.ts
  src/pages/moderators-page/components/main-content/components/filter-section/index.tsx
  src/pages/moderators-page/components/main-content/components/filter-section/styles.module.scss
  src/pages/moderators-page/components/main-content/index.tsx
Labels: enhancement

#78 Companies filters
  src/common/enums/app-route.enum.ts
  src/common/types/company/get-companies-request-query.type.ts
  src/pages/companies-list-page/components/companies-list/components/filter-section/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filter-section/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card-desktop/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/company-card/index.tsx
  src/pages/companies-list-page/components/companies-list/index.tsx
  src/pages/company-details-page/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/components/review/components/review-main/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-stats/index.tsx
  src/pages/course-details-page/index.tsx
  src/pages/home-page/components/main-content/components/companies-section/components/company-card/index.tsx
  src/pages/home-page/components/main-content/components/course-card/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
  src/pages/home-page/components/main-content/components/search-block/helpers/index.ts
  src/pages/home-page/components/main-content/components/search-block/helpers/map-companies.ts
  src/redux/auth/auth-slice.ts
  src/redux/companies/companies-slice.ts
  src/redux/courses/courses-slice.ts
  src/redux/services.ts
Labels: enhancement

#83 Code refactor
  src/common/components/course-card/index.tsx
  src/common/components/expandable-description/index.tsx
  src/common/types/company/company.type.ts
  src/common/types/company/get-company-by-id-response-dto.type.ts
  src/common/types/company/index.ts
  src/common/types/index.ts
  src/pages/company-details-page/components/company-details/components/about/about.tsx
  src/pages/company-details-page/components/company-details/components/about/styles.module.scss
  src/pages/company-details-page/components/company-details/components/contacts/contacts.tsx
  src/pages/company-details-page/components/company-details/components/contacts/styles.module.scss
  src/pages/company-details-page/components/company-details/components/courses/components/course-card/course-card.tsx
  src/pages/company-details-page/components/company-details/components/courses/components/course-card/styles.module.scss
  src/pages/company-details-page/components/company-details/components/courses/courses.tsx
  src/pages/company-details-page/components/company-details/components/courses/styles.module.scss
  src/pages/company-details-page/components/company-details/components/index.ts
  src/pages/company-details-page/components/company-details/components/menu/styles.module.scss
  src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/review-card.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/statistics.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/styles.module.scss
  src/pages/company-details-page/components/company-details/components/reviews/reviews.tsx
  src/pages/company-details-page/components/company-details/components/reviews/styles.module.scss
  src/pages/company-details-page/components/company-details/components/title-logo/styles.module.scss
  src/pages/company-details-page/components/company-details/components/title-logo/title-logo.tsx
  src/pages/company-details-page/components/company-details/index.tsx
  src/pages/company-details-page/components/company-details/styles.module.scss
  src/pages/company-details-page/index.tsx
  src/pages/company-details-page/styles.module.scss
  src/pages/course-details-page/components/main-content/index.tsx
  src/pages/course-details-page/components/main-content/styles.module.scss
  src/pages/course-details-page/index.tsx
  src/pages/course-details-page/styles.module.scss
  src/redux/companies/companies-api.ts
Labels: enhancement

#84 useSearchParams in filters
  src/common/components/sort-dropdown/index.tsx
  src/pages/moderators-page/components/main-content/components/filter-section/index.tsx
  src/pages/moderators-page/components/main-content/components/filter-section/styles.module.scss
  src/pages/moderators-page/components/main-content/index.tsx
Labels: enhancement

#85 added user property policy_agreed and condition on p&p page
  src/common/types/user/user.type.ts
  src/pages/privacy-policy/index.tsx
  src/pages/privacy-policy/styles.module.scss
  src/redux/auth/auth-slice.ts
Labels: enhancement

#88 fix bugs on courses list page
  src/common/components/breadcrumb/styles.module.scss
  src/common/components/check-dropdown/components/subcategory-item/styles.module.scss
  src/common/components/check-dropdown/styles.module.scss
  src/common/components/modal/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-result-items/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-result-title/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-section/index.tsx
  src/pages/course-list-page/components/course-list/index.tsx
  src/pages/course-list-page/components/course-list/styles.module.scss
  src/pages/course-list-page/styles.module.scss
  src/redux/services.ts
Labels: bug

#90 add mutex to auth
  package-lock.json
  package.json
  src/redux/auth/auth-slice.ts
  src/redux/services.ts
Labels: enhancement

#87 feat: added protected rout to moderators page
  src/common/components/index.ts
  src/common/components/protected-route/index.tsx
  src/main.tsx
Labels: enhancement

#91 added tab icon and dynamic tabs title
  public/tab-icon.ico
  public/tab-icon.png
  src/app/App.tsx
  src/common/constants/index.ts
  src/common/constants/tabs.ts
  src/common/helpers/index.ts
  src/common/helpers/update-page-tabs.ts
Labels: enhancement

#92 fix bugs on auth page
  src/pages/auth/index.tsx
  src/pages/auth/styles.module.scss
Labels: bug

#96 Courses categories links and filters
  src/common/components/header/index.tsx
  src/common/constants/tabs.ts
  src/common/enums/app-route.enum.ts
  src/common/types/breadcrumbs.type.ts
  src/common/types/category/category.type.ts
  src/common/types/category/index.ts
  src/common/types/courses/course.type.ts
  src/common/types/index.ts
  src/main.tsx
  src/pages/company-details-page/components/company-details/components/about/about.tsx
  src/pages/company-details-page/components/company-details/index.tsx
  src/pages/course-details-page/components/main-content/components/categories-list/components/category/components/category-item/index.tsx
  src/pages/course-details-page/components/main-content/components/categories-list/components/category/components/category-item/styles.module.scss
  src/pages/course-details-page/components/main-content/components/categories-list/components/category/index.tsx
  src/pages/course-details-page/components/main-content/components/categories-list/components/category/styles.module.scss
  src/pages/course-details-page/components/main-content/components/categories-list/styles.module.scss
  src/pages/course-details-page/components/main-content/components/contacts-bar/components/contact/styles.module.scss
  src/pages/course-details-page/components/main-content/components/contacts-bar/index.tsx
  src/pages/course-details-page/components/main-content/components/contacts-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/description-section/index.tsx
  src/pages/course-details-page/components/main-content/components/description-section/styles.module.scss
  src/pages/course-details-page/components/main-content/components/header/styles.module.scss
  src/pages/course-details-page/components/main-content/components/navigation-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/page-title/index.tsx
  src/pages/course-details-page/components/main-content/components/page-title/styles.module.scss
  src/pages/course-details-page/components/main-content/components/pricing-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-stats/components/rating-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-stats/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-stats/styles.module.scss
  src/pages/course-details-page/components/main-content/components/reviews-bar/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/section-title/styles.module.scss
  src/pages/course-details-page/components/main-content/index.tsx
  src/pages/course-details-page/components/main-content/styles.module.scss
  src/pages/course-details-page/styles.module.scss
  src/pages/course-list-page/components/course-list/index.tsx
Labels: enhancement

#99 Fix bugs
  index.html
  src/common/components/privacy-policy-modal/index.tsx
  src/common/components/search-bar/styles.module.scss
  src/common/components/sort-dropdown/styles.module.scss
  src/common/types/review/course-reviews.type.ts
  src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/review-card.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/statistics.tsx
  src/pages/company-details-page/components/company-details/components/reviews/reviews.tsx
  src/pages/course-details-page/components/main-content/components/categories-list/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/components/review/components/review-header/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/components/review/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-section/index.tsx
  src/pages/course-list-page/components/course-list/styles.module.scss
  src/pages/my-reviews-page/index.tsx
  src/redux/reviews/constants.ts
  src/redux/reviews/reviews-stats-api.ts
  tsconfig.node.tsbuildinfo
  tsconfig.tsbuildinfo
  vite.config.d.ts
  vite.config.js
Labels: enhancement

#101 change send review login for company, changes in styles
  src/pages/company-details-page/components/company-details/components/about/about.tsx
  src/pages/company-details-page/components/company-details/components/about/styles.module.scss
  src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/statistics.tsx
  src/pages/course-details-page/components/main-content/components/navigation-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/page-title/styles.module.scss
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/review-modal/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/index.tsx
  src/pages/course-details-page/components/main-content/index.tsx
  src/pages/course-details-page/components/main-content/styles.module.scss
Labels: enhancement

#103 fix: fix bugs
  src/common/components/breadcrumb/styles.module.scss
  src/common/components/search-bar/index.tsx
  src/common/components/search-input/styles.module.scss
  src/common/components/sort-dropdown/index.tsx
  src/common/components/sort-dropdown/styles.module.scss
  src/common/components/toggle-group-buttons/styles.module.scss
  src/pages/moderators-page/components/main-content/components/filter-section/index.tsx
  src/pages/moderators-page/components/main-content/components/filter-section/styles.module.scss
  src/pages/moderators-page/components/main-content/index.tsx
  src/pages/moderators-page/components/main-content/styles.module.scss
Labels: bug

#102 fix bugs
  src/pages/company-details-page/components/company-details/components/reviews/components/components/review-modal.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/index.tsx
Labels: bug

#105 Not found
  package-lock.json
  package.json
  src/assets/images/404.png
  src/main.tsx
  src/pages/company-details-page/components/company-details/index.tsx
  src/pages/course-details-page/components/main-content/index.tsx
  src/pages/error-fallback/index.tsx
  src/pages/error-fallback/styles.module.scss
  src/pages/index.ts
  src/pages/not-found/index.tsx
  src/pages/not-found/styles.module.scss
Labels: enhancement

#107 Course reviews
  src/common/types/my-reviews/get-my-reviews-params.type.ts
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/reviews-section/index.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/statistics.tsx
  src/pages/course-details-page/components/main-content/components/contacts-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/review-modal/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/index.tsx
  src/pages/course-details-page/components/main-content/styles.module.scss
  src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/components/edit-review-modal/index.tsx
  src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/components/edit-review-modal/styles.module.scss
  src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/components/review-text-section/index.tsx
  src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/components/review-text-section/styles.module.scss
  src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/index.tsx
  src/redux/reviews/reviews-companies-api.ts
  src/redux/reviews/reviews-course-api.ts
  src/redux/store.ts
Labels: enhancement

#108 Fix bugs
  src/common/components/course-card/styles.module.scss
  src/common/components/star-rating/index.tsx
  src/common/components/star-rating/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/styles.module.scss
  src/pages/company-details-page/components/company-details/components/contacts/styles.module.scss
  src/pages/company-details-page/components/company-details/components/courses/courses.tsx
  src/pages/company-details-page/components/company-details/components/courses/styles.module.scss
  src/pages/company-details-page/components/company-details/components/menu/styles.module.scss
  src/pages/company-details-page/components/company-details/components/reviews/components/components/share-modal.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/review-card.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/statistics.tsx
  src/pages/company-details-page/components/company-details/components/reviews/components/styles.module.scss
  src/pages/company-details-page/components/company-details/components/reviews/reviews.tsx
  src/pages/company-details-page/components/company-details/components/reviews/styles.module.scss
  src/pages/company-details-page/components/company-details/components/title-logo/styles.module.scss
  src/pages/company-details-page/components/company-details/components/title-logo/title-logo.tsx
  src/pages/company-details-page/components/company-details/styles.module.scss
  src/pages/course-details-page/components/main-content/components/contacts-bar/index.tsx
  src/pages/course-details-page/components/main-content/components/contacts-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/navigation-bar/styles.module.scss
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/components/review/components/review-header/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/components/review/index.tsx
  src/pages/course-details-page/components/main-content/components/reviews-bar/index.tsx
Labels: enhancement

#110 fix: fix styling bugs, added form validation
  src/common/components/input/index.tsx
  src/common/components/input/styles.module.scss
  src/common/components/toggle-group-buttons/index.tsx
  src/common/hooks/use-app-form.hook.ts
  src/pages/faq-page/components/main-content/components/question-and-answer-section/index.tsx
  src/pages/faq-page/components/main-content/components/question-and-answer-section/styles.module.scss
  src/pages/faq-page/components/main-content/components/send-question/index.tsx
  src/pages/faq-page/components/main-content/components/send-question/styles.module.scss
Labels: bug

#111 fix type in get course reviews query
  src/redux/reviews/reviews-course-api.ts
Labels: bug
