Repository ValentinaTenus/reviewED_fe, pull requests merged in 2024-09, with the labels that each got.

#1 Search element
  src/assets/images/not-found.svg
  src/common/components/dropdown/index.tsx
  src/common/components/dropdown/styles.module.scss
  src/common/components/index.ts
  src/common/components/search-element/components/index.ts
  src/common/components/search-element/index.tsx
  src/common/constants/cities.ts
  src/common/types/company/get-companies-request-query.type.ts
  src/common/types/company/get-company-response-dto.type.ts
  src/common/types/company/index.ts
  src/common/types/courses/course.type.ts
  src/common/types/courses/get-courses-request-query.type.ts
  src/common/types/courses/get-courses-response-dto.type.ts
  src/common/types/courses/index.ts
  src/common/types/dropdown-option/index.ts
  src/common/types/index.ts
  src/main.tsx
  src/pages/home-page/components/main-content/components/index.ts
  src/pages/home-page/components/main-content/components/search-block/components/index.ts
  src/pages/home-page/components/main-content/components/search-block/components/not-found/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/not-found/styles.module.scss
  src/pages/home-page/components/main-content/components/search-block/components/search-element/components/search-input/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/search-element/components/search-input/styles.module.scss
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/search-element/styles.module.scss
  src/pages/home-page/components/main-content/components/search-block/helpers/get-dropdown-options-format.ts
  src/pages/home-page/components/main-content/components/search-block/helpers/index.ts
  src/pages/home-page/components/main-content/components/search-block/helpers/map-companies.ts
  src/pages/home-page/components/main-content/components/search-block/helpers/map-courses.ts
  src/pages/home-page/components/main-content/components/search-block/index.tsx
  src/pages/home-page/components/main-content/components/search-block/styles.module.scss
  src/pages/home-page/components/main-content/index.tsx
  src/redux/companies/companies-api.ts
  src/redux/companies/companies-slice.ts
  src/redux/courses/constants.ts
  src/redux/courses/courses-api.ts
  src/redux/courses/courses-slice.ts
  src/redux/services.ts
  src/redux/store.ts
  vite.config.ts
Labels: enhancement

#2 changed styles
  src/common/components/dropdown/styles.module.scss
  src/common/components/input/styles.module.scss
  src/pages/home-page/components/main-content/components/baner-block/styles.module.scss
  src/pages/home-page/components/main-content/components/search-block/components/not-found/styles.module.scss
  src/pages/home-page/components/main-content/components/search-block/index.tsx
Labels: enhancement

#4 Top companies
  src/assets/styles/variables.scss
  src/common/constants/mock-courses.ts
  src/pages/home-page/components/main-content/components/course-card/index.tsx
  src/pages/home-page/components/main-content/components/course-card/styles.module.scss
  src/pages/home-page/components/main-content/components/index.ts
  src/pages/home-page/components/main-content/components/items-container/styles.module.scss
  src/pages/home-page/components/main-content/components/items-header/styles.module.scss
  src/pages/home-page/components/main-content/components/new-courses-section/components/index.ts
  src/pages/home-page/components/main-content/components/new-courses-section/index.tsx
  src/pages/home-page/components/main-content/components/new-courses-section/styles.module.scss
  src/pages/home-page/components/main-content/components/top-courses-section/index.tsx
  src/pages/home-page/components/main-content/components/top-courses-section/styles.module.scss
  src/pages/home-page/components/main-content/index.tsx
Labels: enhancement

#5 added addCompany section on home page
  src/assets/styles/variables.scss
  src/common/components/button/styles.module.scss
  src/common/components/input/styles.module.scss
  src/pages/home-page/components/main-content/components/add-company/index.tsx
  src/pages/home-page/components/main-content/components/add-company/styles.module.scss
  src/pages/home-page/components/main-content/components/index.ts
  src/pages/home-page/components/main-content/index.tsx
Labels: enhancement

#6 added faq section
  src/assets/images/minus.svg
  src/assets/images/plus.svg
  src/assets/styles/variables.scss
  src/common/components/icon/icon-name-to-svg.ts
  src/common/constants/mock-question-and-answers.ts
  src/common/enums/icon-name.enum.ts
  src/pages/home-page/components/main-content/components/index.ts
  src/pages/home-page/components/main-content/components/question-and-answer-section/components/index.ts
  src/pages/home-page/components/main-content/components/question-and-answer-section/components/question-and-answer-item/index.tsx
  src/pages/home-page/components/main-content/components/question-and-answer-section/components/question-and-answer-item/styles.module.scss
  src/pages/home-page/components/main-content/components/question-and-answer-section/index.tsx
  src/pages/home-page/components/main-content/components/question-and-answer-section/styles.module.scss
  src/pages/home-page/components/main-content/index.tsx
Labels: enhancement

#7 Faq section
  src/common/components/button/index.tsx
  src/common/components/button/styles.module.scss
  src/common/enums/app-route.enum.ts
  src/common/enums/button-variants.enum.ts
  src/pages/home-page/components/main-content/components/companies-section/index.tsx
  src/pages/home-page/components/main-content/components/items-header/index.tsx
  src/pages/home-page/components/main-content/components/new-courses-section/index.tsx
  src/pages/home-page/components/main-content/components/question-and-answer-section/index.tsx
  src/pages/home-page/components/main-content/components/top-courses-section/index.tsx
Labels: enhancement

#8 Footer
  src/assets/images/call.svg
  src/assets/images/facebook.svg
  src/assets/images/iconoir_linkedin.svg
  src/assets/images/logo.svg
  src/assets/images/sms.svg
  src/assets/images/xrp-(xrp).svg
  src/assets/images/youtube.svg
  src/assets/styles/variables.scss
  src/common/components/footer/components/index.ts
  src/common/components/footer/components/navigation-block/index.tsx
  src/common/components/footer/components/navigation-block/styles.module.scss
  src/common/components/footer/components/social-media-links/index.tsx
  src/common/components/footer/components/social-media-links/styles.module.scss
  src/common/components/footer/components/tech-contacts-block/index.tsx
  src/common/components/footer/components/tech-contacts-block/styles.module.scss
  src/common/components/footer/index.tsx
  src/common/components/footer/styles.module.scss
  src/common/components/icon/icon-name-to-svg.ts
  src/common/components/index.ts
  src/common/constants/companies-links.ts
  src/common/constants/courses-links.ts
  src/common/constants/index.ts
  src/common/constants/other-footer-links.ts
  src/common/constants/social-media-links.ts
  src/common/enums/app-route.enum.ts
  src/common/enums/icon-name.enum.ts
  src/common/types/footer-navigation-links/footer-navigation-icon-link.ts
  src/common/types/footer-navigation-links/footer-navigation-link.ts
  src/common/types/footer-navigation-links/index.ts
  src/common/types/index.ts
  src/pages/home-page/components/main-content/styles.module.scss
  src/pages/home-page/index.tsx
  src/pages/home-page/styles.module.scss
Labels: enhancement

#9 Footer
  src/common/components/footer/components/navigation-block/index.tsx
  src/common/components/footer/components/navigation-block/styles.module.scss
  src/common/components/footer/index.tsx
  src/common/components/footer/styles.module.scss
  src/common/constants/cities.ts
  src/common/constants/companies-links/companies-links-desktop.ts
  src/common/constants/companies-links/companies-links-smartphones.ts
  src/common/constants/companies-links/companies-links-tablets.ts
  src/common/constants/companies-links/index.ts
  src/common/constants/courses-links/courses-links-desktop.ts
  src/common/constants/courses-links/courses-links-smartphones.ts
  src/common/constants/courses-links/courses-links-tablets.ts
  src/common/constants/courses-links/index.ts
  src/common/constants/index.ts
  src/pages/home-page/components/header/styles.module.scss
  src/pages/home-page/components/main-content/components/add-company/styles.module.scss
  src/pages/home-page/components/main-content/components/baner-block/index.tsx
  src/pages/home-page/components/main-content/components/baner-block/styles.module.scss
  src/pages/home-page/components/main-content/components/course-card/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/search-element/styles.module.scss
  src/pages/home-page/components/main-content/components/search-block/helpers/map-courses.ts
  src/pages/home-page/components/main-content/components/search-block/index.tsx
  src/pages/home-page/components/main-content/components/search-block/styles.module.scss
  src/pages/home-page/components/main-content/index.tsx
  src/pages/home-page/components/main-content/styles.module.scss
  src/pages/home-page/styles.module.scss
  src/redux/companies/companies-api.ts
  src/redux/courses/courses-api.ts
Labels: enhancement

#11 fix import
  src/pages/home-page/components/main-content/components/baner-block/index.tsx
Labels: enhancement

#12 Search element
  src/assets/styles/normalize.scss
  src/common/components/dropdown/styles.module.scss
  src/common/components/header/components/burger-menu/index.tsx
  src/common/components/header/components/burger-menu/styles.module.scss
  src/common/components/header/components/index.ts
  src/common/components/header/components/search/index.tsx
  src/common/components/header/components/search/styles.module.scss
  src/common/components/header/index.tsx
  src/common/components/header/styles.module.scss
  src/common/components/index.ts
  src/pages/home-page/components/index.ts
  src/pages/home-page/index.tsx
Labels: enhancement

#14 Companies page
  .env.exapmle
  README.md
  eslint.config.js
  src/main.tsx
Labels: enhancement

#15 add moderatorsPage, add Route,
  src/common/enums/app-route.enum.ts
  src/main.tsx
  src/pages/index.ts
  src/pages/moderators-page/componets/index.ts
  src/pages/moderators-page/componets/main-moderators-content/index.tsx
  src/pages/moderators-page/index.tsx
Labels: enhancement

#16 Companies page
  src/assets/images/arrow-right-2.svg
  src/common/components/icon/icon-name-to-svg.ts
  src/common/components/rating/index.tsx
  src/common/components/rating/styles.module.scss
  src/common/enums/icon-name.enum.ts
  src/common/types/company/get-companies-request-query.type.ts
  src/pages/companies-list-page/components/companies-list/components/filter-section/components/companies-categories/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filter-section/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/index.ts
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-table/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/styles.module.scss
  src/pages/companies-list-page/components/companies-list/index.tsx
  src/redux/companies/companies-api.ts
Labels: enhancement

#17 fix styles on home page
  src/assets/images/menu.svg
  src/assets/images/user.svg
  src/common/components/button/styles.module.scss
  src/common/components/footer/components/navigation-block/styles.module.scss
  src/common/components/footer/components/social-media-links/styles.module.scss
  src/common/components/footer/components/tech-contacts-block/index.tsx
  src/common/components/footer/components/tech-contacts-block/styles.module.scss
  src/common/components/footer/styles.module.scss
  src/common/components/header/components/burger-menu/index.tsx
  src/common/components/header/components/burger-menu/styles.module.scss
  src/common/components/header/index.tsx
  src/common/components/header/styles.module.scss
  src/common/components/search-input/styles.module.scss
  src/common/constants/companies-links/companies-links-desktop.ts
  src/common/constants/companies-links/companies-links-smartphones.ts
  src/common/constants/companies-links/companies-links-tablets.ts
  src/common/constants/courses-links/courses-links-desktop.ts
  src/common/constants/courses-links/courses-links-smartphones.ts
  src/common/constants/courses-links/courses-links-tablets.ts
  src/pages/home-page/components/main-content/components/add-company/index.tsx
  src/pages/home-page/components/main-content/components/add-company/styles.module.scss
  src/pages/home-page/components/main-content/components/baner-block/index.tsx
  src/pages/home-page/components/main-content/components/companies-section/index.tsx
  src/pages/home-page/components/main-content/components/course-card/styles.module.scss
  src/pages/home-page/components/main-content/components/items-content-wrapper/styles.module.scss
  src/pages/home-page/components/main-content/components/items-header/index.tsx
  src/pages/home-page/components/main-content/components/top-courses-section/index.tsx
  src/pages/home-page/components/main-content/components/top-courses-section/styles.module.scss
Labels: enhancement

#19 fix companies type in search
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
Labels: bug

#20 Companies page
  src/common/components/index.ts
  src/common/components/rating/index.tsx
  src/common/components/rating/styles.module.scss
  src/common/components/sort-dropdown/index.tsx
  src/common/components/sort-dropdown/styles.module.scss
  src/common/components/star-rating/index.tsx
  src/common/components/star-rating/styles.module.scss
  src/common/constants/companies-sort-options.ts
  src/common/constants/mock-data/mock-user-reviews.ts
  src/common/enums/index.ts
  src/common/enums/star-rating-size.enum.ts
  src/common/enums/star-rating-variants.enum.ts
  src/common/types/company/company.type.ts
  src/common/types/courses/course.type.ts
  src/common/types/index.ts
  src/common/types/review/get-company-and-course-review-by-user-response-dto.type.ts
  src/common/types/review/index.ts
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card-desktop/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card-desktop/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-table/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/company-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/index.ts
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/index.ts
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/reviews-section/index.tsx
  src/pages/companies-list-page/components/companies-list/components/reviews-section/styles.module.scss
  src/pages/companies-list-page/components/companies-list/index.tsx
  src/pages/home-page/components/main-content/components/companies-section/components/company-card/index.tsx
  src/pages/home-page/components/main-content/components/course-card/index.tsx
  src/pages/home-page/components/main-content/index.tsx
  src/redux/companies/companies-api.ts
Labels: enhancement

#22 Companies page
  .husky/pre-commit
  package-lock.json
  package.json
  src/common/components/dropdown/index.tsx
  src/common/components/dropdown/styles.module.scss
  src/common/components/index.ts
  src/common/components/spinner/index.tsx
  src/common/components/spinner/styles.module.scss
  src/common/enums/index.ts
  src/common/enums/spinner-variant.enum.ts
  src/common/types/courses/course.type.ts
  src/common/types/courses/get-courses-request-query.type.ts
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/styles.module.scss
  src/pages/faq-page/components/main-content/components/question-and-answer-section/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
  src/pages/home-page/components/main-content/components/search-block/helpers/index.ts
  src/pages/home-page/components/main-content/components/search-block/helpers/map-companies.ts
  src/pages/home-page/components/main-content/components/search-block/helpers/map-courses-categories.ts
  src/pages/home-page/components/main-content/components/search-block/helpers/map-courses.ts
  src/pages/home-page/components/main-content/components/search-block/helpers/map-locations.ts
  src/pages/home-page/components/main-content/components/search-block/index.tsx
  src/pages/home-page/components/main-content/index.tsx
  src/redux/companies/companies-slice.ts
  src/redux/courses/courses-api.ts
  src/redux/locations/constants.ts
  src/redux/locations/locations-api.ts
  src/redux/locations/locations-slice.ts
  src/redux/store.ts
Labels: enhancement

#23 delete base from vite config
  vite.config.ts
Labels: bug, enhancement

#25 changed route and styles for breadcrumb
  src/common/components/breadcrumb/styles.module.scss
  src/common/components/sort-dropdown/styles.module.scss
  src/common/constants/other-footer-links.ts
  src/common/enums/app-route.enum.ts
  src/pages/companies-list-page/components/companies-list/components/filter-section/components/companies-categories/components/company-category/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-table/styles.module.scss
Labels: enhancement

#30 Pagination
  src/common/components/pagination/index.tsx
  src/common/components/search-bar/index.tsx
  src/common/constants/companies-sort-options.ts
  src/common/enums/companies-per-page-list-view.enum.ts
  src/common/enums/companies-per-page-table-view.enum.ts
  src/common/enums/index.ts
  src/common/types/company/get-companies-request-query.type.ts
  src/pages/companies-list-page/components/companies-list/components/filter-section/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/styles.module.scss
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
  src/redux/companies/companies-api.ts
  src/redux/companies/companies-slice.ts
Labels: enhancement

#31 translated all companies page
  src/common/components/header/index.tsx
  src/common/components/pagination/index.tsx
  src/common/components/pagination/styles.module.scss
  src/common/components/sort-dropdown/index.tsx
  src/common/constants/mock-data/mock-user-reviews.ts
  src/pages/companies-list-page/components/companies-list/components/filter-section/components/companies-categories/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filter-section/components/filter-section-text/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filter-section/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card-desktop/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/company-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/index.tsx
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/index.tsx
  src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/styles.module.scss
  src/pages/companies-list-page/components/companies-list/components/reviews-section/index.tsx
Labels: enhancement

#32 fix bugs
  src/pages/home-page/components/main-content/components/companies-section/index.tsx
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
Labels: bug

#33 added filters for courses
  src/common/types/courses/get-courses-request-query.type.ts
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
  src/redux/courses/courses-api.ts
  src/redux/courses/courses-slice.ts
Labels: enhancement

#34 Auth
  src/app/App.tsx
  src/assets/images/auth-image.png
  src/assets/images/linkedIn-logo.svg
  src/common/components/header/components/burger-menu/index.tsx
  src/common/components/header/components/burger-menu/styles.module.scss
  src/common/components/header/index.tsx
  src/common/components/header/styles.module.scss
  src/common/components/icon/icon-name-to-svg.ts
  src/common/enums/app-route.enum.ts
  src/common/enums/http-methods.enum.ts
  src/common/enums/http-status-code.enum.ts
  src/common/enums/icon-name.enum.ts
  src/common/enums/index.ts
  src/common/hooks/use-get-user.hook.ts
  src/common/types/auth/auth-response-dto.type.ts
  src/common/types/auth/get-tokens-response-dto.type.ts
  src/common/types/auth/index.ts
  src/common/types/auth/login-response-dto.type.ts
  src/common/types/auth/logout-request-dto.type.ts
  src/common/types/index.ts
  src/common/types/user/index.ts
  src/common/types/user/user-with-staff.type.ts
  src/common/types/user/user.type.ts
  src/main.tsx
  src/pages/auth/auth-success.tsx
  src/pages/auth/index.tsx
  src/pages/auth/styles.module.scss
  src/pages/index.ts
  src/redux/auth/auth-api.ts
  src/redux/auth/auth-slice.ts
  src/redux/auth/constants.ts
  src/redux/categories/categories-api.ts
  src/redux/companies/companies-api.ts
  src/redux/courses/courses-api.ts
  src/redux/locations/locations-api.ts
  src/redux/reviews-moderation/reviews-moderation-api.ts
  src/redux/services.ts
  src/redux/store.ts
  src/redux/user/constants.ts
  src/redux/user/user-api.ts
Labels: enhancement

#37 Courses filter
  src/assets/images/close.svg
  src/assets/images/filter.svg
  src/common/components/icon/icon-name-to-svg.ts
  src/common/components/search-bar/index.tsx
  src/common/components/search-bar/styles.module.scss
  src/common/constants/courses-sort-options.ts
  src/common/constants/index.ts
  src/common/enums/icon-name.enum.ts
  src/main.tsx
  src/pages/companies-list-page/components/companies-list/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-section/components/filter-modal/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-section/components/filter-modal/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-section/components/index.ts
  src/pages/course-list-page/components/course-list/components/filter-section/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-section/styles.module.scss
  src/pages/course-list-page/components/course-list/components/index.ts
  src/pages/course-list-page/components/course-list/index.tsx
  src/pages/course-list-page/components/course-list/styles.module.scss
  src/pages/course-list-page/components/index.ts
  src/pages/course-list-page/index.tsx
  src/pages/course-list-page/styles.module.scss
Labels: enhancement

#38 added redirect link query
  .env.exapmle
  src/redux/auth/auth-api.ts
  src/redux/auth/constants.ts
Labels: enhancement

#41 Auth
  src/pages/auth/auth-success.tsx
  src/redux/auth/auth-api.ts
  src/redux/auth/constants.ts
Labels: enhancement

#44 fix bugs
  src/pages/company-details-page/components/company-details/components/about/about.tsx
  src/pages/company-details-page/components/company-details/components/contacts/contacts.tsx
  src/pages/company-details-page/components/company-details/components/courses/courses.tsx
Labels: bug

#48 add isRefreshing to auth state
  src/redux/auth/auth-slice.ts
  src/redux/services.ts
Labels: enhancement

#52 Courses filter
  src/assets/images/half-filled-star.svg
  src/common/components/check-dropdown/index.tsx
  src/common/components/dropdown/index.tsx
  src/common/components/footer/components/navigation-block/styles.module.scss
  src/common/components/footer/components/tech-contacts-block/styles.module.scss
  src/common/components/star-rating/index.tsx
  src/common/components/star-rating/styles.module.scss
  src/common/constants/companies-links/companies-links-desktop.ts
  src/common/constants/companies-links/companies-links-smartphones.ts
  src/common/constants/companies-links/companies-links-tablets.ts
  src/common/enums/courses-filter-type.enum.ts
  src/common/enums/index.ts
  src/common/types/courses/filter.type.ts
  src/common/types/courses/index.ts
  src/common/types/index.ts
  src/pages/course-list-page/components/course-list/components/filter-result-items/components/filter-result-item/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-result-items/components/filter-result-item/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-result-items/components/index.ts
  src/pages/course-list-page/components/course-list/components/filter-result-items/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-result-items/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-result-title/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-result-title/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-section/components/filter-modal/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-section/index.tsx
  src/pages/course-list-page/components/course-list/components/index.ts
  src/pages/course-list-page/components/course-list/index.tsx
  src/pages/course-list-page/components/course-list/styles.module.scss
  src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
  src/redux/courses/courses-api.ts
  src/redux/courses/courses-slice.ts
Labels: enhancement

#55 fix types
  src/pages/company-details-page/components/company-details/index.tsx
Labels: bug

#58 Modal window
  package-lock.json
  src/common/components/index.ts
  src/common/components/modal/index.tsx
  src/common/components/modal/styles.module.scss
  src/pages/course-list-page/components/course-list/components/filter-section/components/filter-modal/index.tsx
  src/pages/course-list-page/components/course-list/components/filter-section/components/filter-modal/styles.module.scss
Labels: enhancement
